### ISSUE TITLE
Service 'org.kde.KWin' does not exist

### ISSUE THREAD

**Issue by nsabir2011** [elsampsa/valkka-core#1]
I tried to install following you installation but this error shows up on ubuntu16.04
'
Service 'org.kde.KWin' does not exist.

Valkka core module is not installed 

(or your version of Valkka Live is _very_ old)

On Ubuntu you can install valkka-core with:

sudo apt-add-repository ppa:sampsa-riikonen/valkka
sudo apt-get update
sudo apt-get install valkka

Or alternatively, just use the following command:

install-valkka-core
'

**Comment by elsampsa** [comment]
Please, type this command into the terminal and press enter:
```
install-valkka-core
```
It will install the valkka-core core modules (written in cpp) to your system from ubuntu repositories.

If that command gives you error messages, please copy-paste your terminal's output here
