### ISSUE TITLE
UDP connect to rtsp 

### ISSUE THREAD

**Issue by suicidesky92** [elsampsa/valkka-core#12]
Hello! By default connection is TCP, but if I heave only UDP rtsp. How I may specify manually UDP protocol to connect rtsp point?

P.S. 'thnx for good project'

**Comment by elsampsa** [comment]
Hi,

Not sure what you mean..

- When you connect with libValkka to an IP cam, it starts **negotiating** with the camera using RTSP protocol, which uses TCP sockets
- Once that negotiation is over, the **video streaming** is done over UDP sockets

This is the standard way of doing things with IP cameras.

What do you want to achieve?  You want the **video streaming** to use TCP sockets as well?

**Comment by suicidesky92** [comment]
Like in ffmpeg key -rtsp_transport (udp/tcp)

**Comment by elsampsa** [comment]
ok..
The normal behaviour (as I just explained), would correspond to
```
-rtsp_transport udp
```
If you wan't to do
```
-rtsp_transport rtsp
```
When you construct your ```LiveConnectionContext``` in python (like in [here](https://elsampsa.github.io/valkka-examples/_build/html/lesson_1.html)), pass it the parameter ```request_tcp = True```

The level-1 API has been contructed in the cpp side, and is available [here](https://elsampsa.github.io/valkka-core/html/structLiveConnectionContext.html#aa762ff0412da0fb5ddf2799914033a6b)
