### ISSUE TITLE
Writing frames into rtsp stream

### ISSUE THREAD

**Issue by ccdsad** [elsampsa/valkka-core#13]
According to lesson number 5, it is possible to receive a rtsp stream and send it to an outgoing rtsp stream. According to lesson number 6, it is possible to record the incoming stream to a file and broadcast the stream from this file. Is it possible to write raw data to the outgoing rtsp stream?

**Comment by elsampsa** [comment]
What do you mean by "write raw data to the outgoing rtsp stream" ?

- In RTSP, the stream is written as packets to (udp) sockets
- Each packet is formatted as RTP
- Do you want to write raw media payload (without rtp formatting) into a socket..?

If this is the case, then I guess you are trying to achieve some dodgy way of inter-process communication (rotating raw media stream through sockets to another process).  There's no need for such stunts in libValkka, as you can get your media payload and timestamps to python side.

Please specify what you are trying to do.

**Comment by ccdsad** [comment]
comes out with the help of this library can I only create a stream from a file or an incoming stream? Is it possible to make outgoing rtsp stream from already readed frames in numpy arrays?
Thank you for your answers.

**Comment by elsampsa** [comment]
With "already read frames in numpy arrays" you are referring to bitmap (i.e images), or H264 encoded stream (packets)?

If you want to turn bitmap images into H264 encoded stream, you need ENcoding.

- In libValkka we assume that the frames are always H264 encoded (they come typically from an IP camera, or from a disk storage where they have been saved as H264 as well)
- ..so we only do DEcoding (i.e. from H264 => image)
- At the moment, there is no ENcoding (image => H264), for various reasons, one being the licensing issues of the x264 encoder.

Or do you just want to transmit some H264 encoded video you get outside libValkka?

**Comment by ccdsad** [comment]
Yes, I want to transmit some H264 encoded video you get outside libValkka?

**Comment by elsampsa** [comment]
Ok, thanks for the clarification.

At the moment, payload can be pushed to the python side:
```
cpp side => shared memory => python side
```
But unfortunately, this one:
```
python side => shared memory => cpp side
```
has not been implemented.

A nice feature though.  Payload could be pushed from python side to the libValkka infrastructure.

We can put it into a wishlist.  Do you have time for this @eranpet .. ?  If anyone wants to pay for this, it can be prioritized.  :)

**Comment by ccdsad** [comment]
Thank you for answers!
