### ISSUE TITLE
Support for Windows and/or Mac

### ISSUE THREAD

**Issue by samjosephkpl** [elsampsa/valkka-core#16]
Hello, great work. Is it easy to make this work on a Windows or Mac machine? Thanks!

**Comment by elsampsa** [comment]
> Is it easy to make this work on a Windows or Mac machine? Thanks!

Currently this is not in our near or far future plans.  There are thousands of other priorities.

Generally speaking, libValkka is based on OpenGL, live555, ffmpeg, etc., which work on windows / mac as well.. (current live555 support I'm not sure in fact).

However, there are many posix-specific parts, like semaphores & shared memory, and I'd imagine that these are not available in windows.

So, to answer your question, no, it's not easy.  I'm not even 100% sure if it's possible.
