### ISSUE TITLE
Extracting NTP timestamp from rtsp

### ISSUE THREAD

**Issue by nik13** [elsampsa/valkka-core#27]
While using RTSP for playback from an onvif device, the playback does not play accurately.

From this manual: https://www.onvif.org/specs/stream/ONVIF-Streaming-Spec.pdf

_In order to allow clients to report a stable and accurate timestamp for each frame played back regardless of the direction of playback, it is necessary to associate an absolute timestamp with each packet, or each group of packets with the same RTP timestamp (e.g. a video frame). This is achieved using an RTP header extension containing an NTP timestamp._

I followed this: https://stackoverflow.com/questions/28022432/receiving-rtp-packets-after-rtsp-setup , but  no success. 

How can I decode the headers or fetch the NTP timestamp from the packets or frames?

**Comment by elsampsa** [comment]
https://elsampsa.github.io/valkka-examples/_build/html/lesson_4.html#client-side-opencv

There is ``meta.mstimestamp``

**Comment by nik13** [comment]
Hi @elsampsa , thanks for the replay. 

What I'm looking for is the time when the feed was recording in an onvif device. 
If I'm not wrong, this timestamp is the presentation time to the user wrt to when the stream was played? 

Correct me if I'm wrong.

**Comment by elsampsa** [comment]
What on earth is "time when the feed was *recording* in an onvif device" ?   Something that some onvif device (camera? server?) has recorded internally?

There is no ready-made thing in libValkka to handle something that has been recorded on some onvif device.

We're just getting live streams from RTSP cameras here.

If you need to play with OnVif, please take a look at [this](https://elsampsa.github.io/valkka-examples/_build/html/onvif.html)

**Comment by nik13** [comment]
By "time when the feed was recording in an onvif device" I mean the video playback options that are generally available in onvif devices. You can gave a look here: https://www.onvif.org/specs/stream/ONVIF-Streaming-Spec.pdf in the playback section. 

Thanks for the help anyway. I solved it by using plain socket requests.
