### ISSUE TITLE
ModuleNotFoundError: No module named 'valkka.core'

### ISSUE THREAD

**Issue by deepik27** [elsampsa/valkka-core#28]
File "lesson_1_a.py", line 12, in <module>
    from valkka.core import *
ModuleNotFoundError: No module named 'valkka.core'

**Comment by elsampsa** [comment]
*phew!* You scared the *shit* out of me..  I thought that the PPA is broken..!  

But it ain't.

Have you, by any chance, followed this?: https://elsampsa.github.io/valkka-examples/_build/html/requirements.html

Once you actually install libValkka you can try from command line:
```
python3
from valkka.core import *
```
I suggest that you also run the "quicktest.py" as instructed in that same page.

**Comment by deepik27** [comment]
Actually valkka supports Ubuntu 20 and python 3.8 version

**Comment by elsampsa** [comment]
If you have several python versions installed into your system, you can start python 3.8 by typing:
```
python3.8
```
If you really need to use some other python version than the system's default one, you can also compile libValkka yourself: it's very easy, please see the front-page of this repo.

**Comment by deepik27** [comment]
yeah thanks so much got it ran well quicktest.py file
