### ISSUE TITLE
Onvif  support 

### ISSUE THREAD

**Issue by lchunleo** [elsampsa/valkka-core#32]
I had consulted the onvif examples for the valkka but however I  faced some issue trying to get events and also video analytics data (metadata of detection ) .

I also try to get video analytics information but it seem not all r working w my cam. If I wish to get the device mgmt and video analytics , is is correct  I have to instantiate class for both of them 

 Do you have some examples to show case this ? Thank you v much .

  I

**Comment by jjehl** [comment]
Maybe pasting some code you use make an answer more possible.

**Comment by elsampsa** [comment]
I think video analytics data can be some very vendor-specific flavor of OnVif.  Myself I have ever only played with device management, etc. basic stuff that seems to be working well.  I remember that many onvif calls carry a timestamp & if the timestamp is not consistent with the cameras/devices time, then the calls might not work (I encountered this when doing PTZ with axis cameras).  Syncing server (say your laptop) and device (camera) time can be tricky: sometimes you need to establish your laptop as NTP time server which the camera then uses.

And yes, you can create several onvif instances.

**Comment by elsampsa** [comment]
and yes, example code wouldn't hurt.
