### ISSUE TITLE
No apt release file for Ubuntu 22.04

### ISSUE THREAD

**Issue by goigle** [elsampsa/valkka-core#34]
## Bug report

I was following the [guide here](https://valkka.readthedocs.io/en/latest/requirements.html#install-valkka-core) to install on Ubuntu and ran into this issue.

`sudo apt update` output
   
 ```
Hit:1 http://us.archive.ubuntu.com/ubuntu jammy InRelease  
Get:2 http://us.archive.ubuntu.com/ubuntu jammy-updates InRelease [114 kB]  
Get:3 http://us.archive.ubuntu.com/ubuntu jammy-backports InRelease [99.8 kB]   
Get:4 http://us.archive.ubuntu.com/ubuntu jammy-security InRelease [110 kB]  
Ign:5 https://ppa.launchpadcontent.net/sampsa-riikonen/valkka/ubuntu jammy InRelease   
Err:6 https://ppa.launchpadcontent.net/sampsa-riikonen/valkka/ubuntu jammy Release  
  404  Not Found [IP: 185.125.190.52 443]  
Reading package lists... Done  
E: The repository 'https://ppa.launchpadcontent.net/sampsa-riikonen/valkka/ubuntu jammy Release' does not have a Release file.  
N: Updating from such a repository can't be done securely, and is therefore disabled by default.  
N: See apt-secure(8) manpage for repository creation and user configuration details.  
```

**Comment by elsampsa** [comment]
ok, 22.04 is also LTS distro.  I'll try to work out this issue this week.   Thanks for noticing.

**Comment by Soum-Soum** [comment]
I have the same problem. 

Thank you for your quick response! :)

**Comment by elsampsa** [comment]
When I try to compile in Ubuntu 22.04 (the ancient version of) ffmpeg (that libValkka uses), I stumble upon:
```
sys/sysctl.h : no such file or directory
```
It seems that ``sysctl.h`` is deprecated in the newer linux versions, while still in Ubuntu 20.04 libValkka compiles just fine.

Not sure how long (update ffmpeg version? - fair amount of work) fixing this problem could take.  

Help would be appreciated: if you're using Ubuntu 22, try to compile from source & figure out of there's any quick fix to this (compiling libValkka from source is very easy - see the valkka-core docs).

**Comment by elsampsa** [comment]
A tentative binary package now avail. for ubuntu 22:

https://launchpad.net/~sampsa-riikonen/+archive/ubuntu/valkka/+packages

So sudo apt etc. commands using that PPA repo should  now work from ubuntu 22.

Have not tested thoroughly & will do that when I get back to my IP cams.  Please reopen ticket if there's something wrong.
