### ISSUE TITLE
Subscribing to an RTP Stream and Re-publishing It Through an RTSP Server

### ISSUE THREAD

**Issue by jonathanleinola** [elsampsa/valkka-core#63]
### Background:
I have been working on a project where the goal is to subscribe to an RTP stream, potentially provided via an SDP file, and then re-publish this stream through an RTSP server. Previously, I utilized GStreamer for this purpose, but encountered several challenges that were difficult to debug.

### Question:
Does Valkka support the functionality to directly handle and republish RTP streams as described above? Specifically, I'm interested in:

-Subscribing to an RTP stream using details from an SDP file.
-Republishing that stream via an RTSP server using Valkka.

If Valkka supports these features, could you also provide some insights or examples on how this could be implemented?

Thank you for your assistance!

**Comment by elsampsa** [comment]
Never tried this exact permutation myself, but in principle, it should work.

Your starting point is [this tutorial example](https://elsampsa.github.io/valkka-examples/_build/html/lesson_5.html#using-the-rtsp-server).

You should first test that one, i.e. get stream from a local IP camera and then see if the established RTSP server (that forwards the said stream) works OK.

After that, you would change the source type in `LiveConnectionContext` from RTSP camera into SDP file:  `LiveConnectionContext` accepts two type of connections: `rtsp` and `sdp` (see [here](https://elsampsa.github.io/valkka-core/html/group__livethread__tag.html#ga393bb55d7e6d624a2e428e600fbea26c)).
