### ISSUE TITLE
Using with Raspberry Pi

### ISSUE THREAD

**Issue by cbasavaraj** [elsampsa/valkka-core#9]
Hi, 
Your libraries looks very promising. Do you think I can use them with a Raspberry Pi? If I can launch an RTSP stream from a Pi by using GStreamer or ffmpeg, it should work right? Thanks

**Comment by elsampsa** [comment]
Yes, it should..!

The ready-made binary .deb packages [here](https://launchpad.net/~sampsa-riikonen/+archive/ubuntu/valkka/+packages) (which you can install with ```apt-get```) only work with canonical's products, so I'd imagine they work with "Ubuntu Mate" that's for rasbperry pi.  

If you're using a non-ubuntu distro, then you must compile libValkka on the raspberry pi by yourself.  

..but that should be straightforward.  Just follow the instructions on this repo's page.  And let me know how the compilation is going, so I can help you with any issues.

**Comment by cbasavaraj** [comment]
Thanks for the reply! I won't be trying this right now, but likely over the next few months. Will get back to you if I have any issues. Thanks again.

**Comment by elsampsa** [comment]
At this stage, libValkka seems to compile ok for arm devices, so will be closing this.

**Comment by PeterZhel** [comment]
Hi guys!
I have recently compiled it without problems on Rpi 4, but it has i965-va-driver dependency that could not be satisfied.

**Comment by elsampsa** [comment]
This was expected.. we should add some if-then-else's here, depending on the detected architecture:

https://github.com/elsampsa/valkka-core/blob/master/ext/configure_ffmpeg.bash

Testing the build (again) with this:

https://github.com/elsampsa/valkka-core/blob/master/docker/README.md

Not sure when I have time to do this.. maybe next week.

**Comment by elsampsa** [comment]
as of version 1.5.4 ``easy_build.bash`` should again work in arm
